# Generated by Django 5.2 on 2025-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('laptops', 'Laptops'), ('desktops', 'Desktops'), ('printers', 'Printers'), ('accessories', 'Accessories')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
